#!/usr/bin/env python3
"""Write each named crate's SUPPLY-CHAIN.md, beside its manifest, from supply-chain/.

For every crate a published crate depends on -- at build time or run
time -- the report says how its code is vouched for: an audit imported
from an organisation that publishes them, a publisher those organisations
trust, or an exemption, with the evidence recorded in the exemption's
notes. It also marks the dependencies that run code while compiling
(a build script or a procedural macro).

The report is a view of what `cargo vet` enforces, never edited by hand:
`make supply-chain` regenerates it, and CI fails if the committed copy is
stale (`make supply-chain-check`).

Adapted from publet's tools/supply-chain-report.py: the crates are named
as arguments, each report goes beside its crate's manifest, and the
dependencies counted are those built for any target.

Usage: tools/supply-chain-report.py [--check] CRATE...
"""

import json
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAIN = ROOT / "supply-chain"


def load(name):
    with open(CHAIN / name, "rb") as f:
        return tomllib.load(f)


def metadata():
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        capture_output=True, text=True, check=True, cwd=ROOT).stdout
    return json.loads(out)


def dependencies(meta, crate):
    """Every registry crate `crate` needs to build and run, with flags.

    Resolved with `cargo tree -p`, so features are those `crate` itself
    enables: what a user depending on it alone builds, not what other
    workspace members switch on. Every target counts, so a dependency built
    only on some platforms is listed; one that is locked but never built,
    such as an optional dependency nothing enables, is not.
    """
    out = subprocess.run(
        ["cargo", "tree", "--locked", "-q", "-p", crate, "-e", "normal,build", "--target", "all",
         "--prefix", "none", "--format", "{p}"],
        capture_output=True, text=True, check=True, cwd=ROOT).stdout
    wanted = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1].startswith("v") and "(/" not in line:
            wanted.add((parts[0], parts[1][1:]))
    kinds = {}
    for pkg in meta["packages"]:
        if pkg.get("source") is not None:
            kinds[(pkg["name"], pkg["version"])] = {
                k for t in pkg["targets"] for k in t["kind"]}
    return sorted(
        ({"name": n, "version": v,
          "build_script": "custom-build" in kinds.get((n, v), set()),
          "proc_macro": "proc-macro" in kinds.get((n, v), set())}
         for n, v in wanted),
        key=lambda d: (d["name"], d["version"]))


def imported_audits(imports, name, version):
    """Organisations whose imported audit covers exactly this version."""
    orgs = []
    for org, data in imports.get("audits", {}).items():
        for audit in data.get("audits", {}).get(name, []):
            if audit.get("version") == version or (
                    audit.get("delta", "").split("->")[-1].strip() == version):
                orgs.append(org)
    return sorted(set(orgs))


def status(dep, config, audits, imports):
    name, version = dep["name"], dep["version"]
    for ex in config.get("exemptions", {}).get(name, []):
        if ex["version"] == version:
            return "not audited (exempt)", ex.get("notes", "")
    for audit in audits.get("audits", {}).get(name, []):
        if audit.get("version") == version or (
                audit.get("delta", "").split("->")[-1].strip() == version):
            return "audited by this project", audit.get("notes", "")
    trusted = audits.get("trusted", {}).get(name, [])
    if trusted:
        publishers = [p for p in imports.get("publisher", {}).get(name, [])
                      if p["version"] == version]
        who = publishers[0]["user-login"] if publishers else "its publisher"
        return f"trusted publisher ({who})", trusted[0].get("notes", "")
    orgs = imported_audits(imports, name, version)
    if orgs:
        return "audited by " + ", ".join(orgs), ""
    return "audited (a chain of imported audits)", ""


def report(crate, deps, config, audits, imports):
    lines = [
        f"# Supply chain: {crate}",
        "",
        "Generated by `tools/supply-chain-report.py` from `supply-chain/`; do not edit.",
        "",
        "Every crate this one needs to build and run, and how its code is vouched for,",
        "as `cargo vet` enforces it in CI. Audits are imported from Mozilla, Google, the",
        "Bytecode Alliance, Zcash, ISRG and Embark Studios. A trusted publisher is one",
        "those organisations trust, or this project's own author; the evidence column",
        "says which. *Build-time code* marks a build script (B) or a procedural macro",
        "(P): code that runs while compiling.",
        "",
        "| Crate | Version | Build-time code | Status | Evidence |",
        "|---|---|---|---|---|",
    ]
    counts = {}
    for dep in deps:
        state, notes = status(dep, config, audits, imports)
        key = ("exempt" if state.startswith("not audited")
               else "trusted publisher" if state.startswith("trusted")
               else "audited")
        counts[key] = counts.get(key, 0) + 1
        build = "".join(f for f, on in (("B", dep["build_script"]), ("P", dep["proc_macro"])) if on) or "-"
        lines.append(f"| `{dep['name']}` | {dep['version']} | {build} | {state} | {notes} |")
    summary = ", ".join(f"{n} {k}" for k, n in sorted(counts.items()))
    lines[3:3] = [f"{len(deps)} dependencies: {summary}."]
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    crates = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not crates:
        sys.exit("name the crates to report on: tools/supply-chain-report.py [--check] CRATE...")
    config, audits, imports = load("config.toml"), load("audits.toml"), load("imports.lock")
    meta = metadata()
    stale = []
    dirs = {p["name"]: Path(p["manifest_path"]).parent
            for p in meta["packages"] if p.get("source") is None}
    for crate in crates:
        text = report(crate, dependencies(meta, crate), config, audits, imports)
        path = dirs[crate] / "SUPPLY-CHAIN.md"
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit("stale; run `make supply-chain`: " + ", ".join(stale))


if __name__ == "__main__":
    main()
